#!/usr/bin/env bash
# A script to Install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy
config=\
'
backend selasi-backend
        balance roundrobin
        server 192925-web-01 3.90.70.66:80 check
        server 192925-web-02 100.26.231.45:80 check
frontend selasi-frontend
        bind *:80
        mode http
        default_backend selasi-backend
'
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
