#!/usr/bin/env bash
# A Bash that displays numbers from 1 to 100.

i=1
while ((i < 101))
do
	if ((i % 3 == 0 && i % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((i % 3 == 0))
	then
		echo "Fizz"
	elif ((i % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	((i++))
done
