#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes

hour=0
while ((hour <= 12 ))
do
	echo "Hour: $hour"
	minute=1
	while ((minute < 60))
	do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
